version: '2'
services:
    coivit-app:
        image: coivit
        external_links:
            - coivit-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/coivit?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    coivit-mysql:
        extends:
            file: mysql.yml
            service: coivit-mysql
