version: '2'
services:
    admincarpooling_mcbd-app:
        image: admincarpooling_mcbd
        external_links:
            - admincarpooling_mcbd-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/admincarpooling_mcbd?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    admincarpooling_mcbd-mysql:
        extends:
            file: mysql.yml
            service: admincarpooling_mcbd-mysql
